version: '3.8'

services:
  redis:
    image: redis:6.2.6
    restart: on-failure
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 3
